### ISSUE TITLE
Android - js 测试结果

### ISSUE THREAD

**Issue by tinybearc** [sdkbox/sdkbox-sample-agecheq#4]
### agecheq 版本：2.1.3.2

一个按钮：check

输出log：

```
03-29 22:47:43.356  6149  6177 D cocos2d-x debug info: JS: check
03-29 22:47:43.373  6149  6262 W System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
03-29 22:47:43.374  6149  6264 W System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
03-29 22:47:43.374  6149  6262 W System  : ClassLoader referenced unknown path: /system/framework/com.qualcomm.qti.GBAHttpAuthentication.jar
03-29 22:47:51.338  6149  6264 E dbgAcheqLib: E2:Unable to resolve host "api.agecheq.com": No address associated with hostname
03-29 22:47:51.338  6149  6264 W System.err: java.net.UnknownHostException: Unable to resolve host "api.agecheq.com": No address associated with hostname
03-29 22:47:51.344  6149  6264 W System.err:    at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
03-29 22:47:51.344  6149  6264 W System.err:    at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
03-29 22:47:51.344  6149  6264 W System.err:    at java.net.InetAddress.getAllByName(InetAddress.java:215)
03-29 22:47:51.345  6149  6264 W System.err:    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:142)
03-29 22:47:51.345  6149  6264 W System.err:    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
03-29 22:47:51.345  6149  6264 W System.err:    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
03-29 22:47:51.345  6149  6264 W System.err:    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:370)
03-29 22:47:51.345  6149  6264 W System.err:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
03-29 22:47:51.346  6149  6264 W System.err:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
03-29 22:47:51.346  6149  6264 W System.err:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
03-29 22:47:51.346  6149  6264 W System.err:    at com.agecheq.agecheqlib.AgeCheqApi$1.run(AgeCheqApi.java:97)
03-29 22:47:51.347  6149  6264 W System.err:    at java.lang.Thread.run(Thread.java:818)
03-29 22:47:51.347  6149  6264 W System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
03-29 22:47:51.352  6149  6264 W System.err:    at libcore.io.Posix.android_getaddrinfo(Native Method)
03-29 22:47:51.354  6149  6264 W System.err:    at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
03-29 22:47:51.354  6149  6264 W System.err:    at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
03-29 22:47:51.354  6149  6264 W System.err:    ... 11 more
03-29 22:47:51.360  6149  6264 E dbgAgeCheqLib: Error parsing data: org.json.JSONException: End of input at character 0 of
03-29 22:47:51.362  6149  6264 D dbgAgeCheqLib: Exception delivering data:Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference
03-29 22:47:51.362  6149  6264 D dbgAgeCheq: call listener
03-29 22:47:51.370  6149  6177 D cocos2d-x debug info: JS: associateDataResponse rtn: rtnmsg:
03-29 22:47:57.153  6149  6262 E dbgAcheqLib: E2:Unable to resolve host "api.agecheq.com": No address associated with hostname
03-29 22:47:57.153  6149  6262 W System.err: java.net.UnknownHostException: Unable to resolve host "api.agecheq.com": No address associated with hostname
03-29 22:47:57.154  6149  6262 W System.err:    at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
03-29 22:47:57.154  6149  6262 W System.err:    at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
03-29 22:47:57.154  6149  6262 W System.err:    at java.net.InetAddress.getAllByName(InetAddress.java:215)
03-29 22:47:57.155  6149  6262 W System.err:    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:142)
03-29 22:47:57.155  6149  6262 W System.err:    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
03-29 22:47:57.155  6149  6262 W System.err:    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
03-29 22:47:57.155  6149  6262 W System.err:    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:370)
03-29 22:47:57.155  6149  6262 W System.err:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
03-29 22:47:57.156  6149  6262 W System.err:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
03-29 22:47:57.156  6149  6262 W System.err:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
03-29 22:47:57.156  6149  6262 W System.err:    at com.agecheq.agecheqlib.AgeCheqApi$1.run(AgeCheqApi.java:97)
03-29 22:47:57.156  6149  6262 W System.err:    at java.lang.Thread.run(Thread.java:818)
03-29 22:47:57.157  6149  6262 W System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
03-29 22:47:57.157  6149  6262 W System.err:    at libcore.io.Posix.android_getaddrinfo(Native Method)
03-29 22:47:57.158  6149  6262 W System.err:    at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
03-29 22:47:57.158  6149  6262 W System.err:    at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
03-29 22:47:57.158  6149  6262 W System.err:    ... 11 more
03-29 22:47:57.158  6149  6262 E dbgAgeCheqLib: Error parsing data: org.json.JSONException: End of input at character 0 of
03-29 22:47:57.173  6149  6262 D dbgAgeCheqLib: Exception delivering data:Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference
03-29 22:47:57.173  6149  6262 D dbgAgeCheq: call listener
03-29 22:47:57.182  6149  6177 D cocos2d-x debug info: JS: checkResponse rtn: rtnmsg: apiversion:0 checktype:0 appauthorized:false appblocked:false parentverified:0 under13:false under18:false underdevage:false trials:-1360715312
```

**Comment by hugohuang1111** [comment]
Unable to resolve host "api.agecheq.com": No address associated with hostname

测试设置的网络不对，没联上网，
