### ISSUE TITLE
Android - lua 测试结果

### ISSUE THREAD

**Issue by tinybearc** [sdkbox/sdkbox-sample-agecheq#6]
### agecheq 版本：2.1.3.2

一个按钮：check

输出log：

```
03-29 22:54:56.720  7488  7532 D cocos2d-x debug info: [LUA-print] check
03-29 22:54:56.739  7488  7688 W System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
03-29 22:54:56.742  7488  7688 W System  : ClassLoader referenced unknown path: /system/framework/com.qualcomm.qti.GBAHttpAuthentication.jar
03-29 22:54:56.745  7488  7689 W System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
03-29 22:55:09.204  7488  7689 E dbgAcheqLib: E2:Unable to resolve host "api.agecheq.com": No address associated with hostname
03-29 22:55:09.204  7488  7689 W System.err: java.net.UnknownHostException: Unable to resolve host "api.agecheq.com": No address associated with hostname
03-29 22:55:09.214  7488  7689 W System.err:    at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
03-29 22:55:09.214  7488  7689 W System.err:    at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
03-29 22:55:09.214  7488  7689 W System.err:    at java.net.InetAddress.getAllByName(InetAddress.java:215)
03-29 22:55:09.214  7488  7689 W System.err:    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:142)
03-29 22:55:09.215  7488  7689 W System.err:    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
03-29 22:55:09.215  7488  7689 W System.err:    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
03-29 22:55:09.215  7488  7689 W System.err:    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:370)
03-29 22:55:09.215  7488  7689 W System.err:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
03-29 22:55:09.216  7488  7689 W System.err:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
03-29 22:55:09.216  7488  7689 W System.err:    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
03-29 22:55:09.216  7488  7689 W System.err:    at com.agecheq.agecheqlib.AgeCheqApi$1.run(AgeCheqApi.java:97)
03-29 22:55:09.216  7488  7689 W System.err:    at java.lang.Thread.run(Thread.java:818)
03-29 22:55:09.217  7488  7689 W System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
03-29 22:55:09.227  7488  7689 W System.err:    at libcore.io.Posix.android_getaddrinfo(Native Method)
03-29 22:55:09.227  7488  7689 W System.err:    at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
03-29 22:55:09.230  7488  7689 W System.err:    at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
03-29 22:55:09.230  7488  7689 W System.err:    ... 11 more
03-29 22:55:09.234  7488  7689 E dbgAgeCheqLib: Error parsing data: org.json.JSONException: End of input at character 0 of
03-29 22:55:09.235  7488  7689 D dbgAgeCheqLib: Exception delivering data:Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference
03-29 22:55:09.236  7488  7689 D dbgAgeCheq: call listener
03-29 22:55:09.240  7488  7532 D cocos2d-x debug info: [LUA-print] dump from: [string "app/views/MainScene.lua"]:26: in function <[string "app/views/MainScene.lua"]:22>
03-29 22:55:09.240  7488  7532 D cocos2d-x debug info: [LUA-print] - "<var>" = {
03-29 22:55:09.240  7488  7532 D cocos2d-x debug info: [LUA-print] -     "event"  = "associateDataResponse"
03-29 22:55:09.240  7488  7532 D cocos2d-x debug info: [LUA-print] -     "rtn"    = ""
03-29 22:55:09.241  7488  7532 D cocos2d-x debug info: [LUA-print] -     "rtnmsg" = ""
03-29 22:55:09.241  7488  7532 D cocos2d-x debug info: [LUA-print] - }
```

**Comment by hugohuang1111** [comment]
Unable to resolve host "api.agecheq.com": No address associated with hostname

出现这个错，应该是测试设备的网络没有通
